apiVersion: v2
type: application
name: observability-stack-k3s
version: 0.1.0
description: Observability stack in k3s
sources:
  - https://github.com/fagnercarvalho/observability-stack-k3s
maintainers:
  - name: fagnercarvalho
appVersion: "1.0.0"
dependencies:
  - name: opentelemetry-collector
    version: "0.110.3"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
  - name: grafana
    version: "8.10.0"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: tempo
    alias: tempo
    version: "1.18.1"
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
  - name: prometheus
    version: "27.3.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: loki
    alias: loki
    version: "6.24.0"
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: pyroscope
    alias: pyroscope
    version: "1.12.0"
    repository: https://grafana.github.io/helm-charts
    condition: pyroscope.enabled