opentelemetry-collector:
  mode: deployment

  image:
    repository: "otel/opentelemetry-collector-k8s"

  replicaCount: 1

  resources:
    limits:
      memory: 200Mi

  ingress:
    enabled: true
    ingressClassName: "traefik"
    hosts:
      - host: local.otel
        paths:
          - path: /
            pathType: Prefix
            port: 80
          - path: /
            pathType: Prefix
            port: 4317 # gRPC receiver
          - path: /
            pathType: Prefix
            port: 4318 # HTTP receiver